export enum CATEGORY {
    STUDY_SPACE = "STUDY_SPACE",
    LIBRARY = "LIBRARY",
    FOOD_SERVICE = "FOOD_SERVICE",
    SPORTS = "SPORTS",
    STUDENT_SERVICE = "STUDENT_SERVICE",
    COMPUTER_LAB = "COMPUTER_LAB",
    OTHER = "OTHER"
}

export enum STATE{
    ACTIVE = "ACTIVE",
    TEMPORARILY_CLOSED = "TEMPORARILY_CLOSED",
    INACTIVE = "INACTIVE"
}