### Creer une place
POST http://localhost:3000/api/v1/places
Content-Type: application/json

{
    "name": "u",
    "description": "test2",
    "category": "OTHER",
    "address": "Test rue du test, Montreal"  
}

### Get tout les place
GET http://localhost:3000/api/v1/places

### Get by id
Get http://localhost:3000/api/v1/places/d18d1101-8ea2-4e8fa362-c678569024a5

### Update une place
PATCH  http://localhost:3000/api/v1/places/update/c3a50bdb-43e8-4a1c-8d64-65226be86535
Content-Type: application/json

{
    "name": "UpdateTest",
    "description": "UpdateTest",
    "category": "STUDY_SPACE",
    "address": "Test rue du test, Montreal",
    "status": "ACTIVE"
}
